# Generated by Django 4.2.20 on 2026-02-23 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TraceJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gambar_asli', models.ImageField(upload_to='uploads/')),
                ('file_vektor', models.FileField(blank=True, null=True, upload_to='vektor_output/')),
                ('is_paid', models.BooleanField(default=False)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trace Job',
                'verbose_name_plural': 'Trace Jobs',
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='TopUpTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominal', models.IntegerField(help_text='Jumlah saldo yang ingin ditambahkan (Rupiah)')),
                ('bukti_transfer', models.ImageField(help_text='Screenshot/foto bukti transfer', upload_to='buktibayar/')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('verified', 'Terverifikasi'), ('rejected', 'Ditolak')], default='pending', max_length=10)),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topup_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Top-Up Transaction',
                'verbose_name_plural': 'Top-Up Transactions',
                'ordering': ['-tanggal'],
            },
        ),
    ]
